class PagesController < ApplicationController
   def about
    @title = 'About us'
    @paragraph = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus accumsan tortor posuere ac ut consequat semper viverra. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Diam maecenas sed enim ut.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Luctus accumsan tortor posuere ac ut consequat semper viverra. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Diam maecenas sed enim ut. Aliquet nec ullamcorper sit amet. Nisl nisi scelerisque eu ultrices. Ante metus dictum at tempor. Malesuada fames ac turpis egestas maecenas pharetra convallis. Consequat interdum varius sit amet mattis vulputate. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. '
    @content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget nulla facilisi etiam dignissim diam. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Purus semper eget duis at. Facilisi nullam vehicula ipsum a arcu. Eget duis at tellus at urna. Augue lacus viverra vitae congue eu. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Aliquam faucibus purus in massa. Eu nisl nunc mi ipsum faucibus vitae aliquet. Netus et malesuada fames ac.

      Hendrerit gravida rutrum quisque non tellus orci ac auctor. Platea dictumst quisque sagittis purus sit amet. At in tellus integer feugiat. Massa ultricies mi quis hendrerit. Volutpat lacus laoreet non curabitur. Iaculis at erat pellentesque adipiscing. Mi ipsum faucibus vitae aliquet nec. Donec adipiscing tristique risus nec feugiat in. Netus et malesuada fames ac turpis egestas maecenas pharetra. Diam sollicitudin tempor id eu nisl nunc.
      
      Purus in mollis nunc sed. Lobortis feugiat vivamus at augue. In metus vulputate eu scelerisque. Aliquam etiam erat velit scelerisque. Tellus elementum sagittis vitae et leo. Aliquet risus feugiat in ante metus dictum at tempor commodo. Et egestas quis ipsum suspendisse. Donec pretium vulputate sapien nec sagittis aliquam. Massa tincidunt dui ut ornare. Orci nulla pellentesque dignissim enim. Dictum non consectetur a erat nam at lectus urna. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vitae aliquet nec ullamcorper sit amet risus nullam. Et magnis dis parturient montes nascetur ridiculus.
      
      Eget nullam non nisi est sit amet facilisis magna. Felis eget velit aliquet sagittis id consectetur. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Venenatis lectus magna fringilla urna porttitor. Eros in cursus turpis massa tincidunt dui ut. Diam sit amet nisl suscipit adipiscing. Nunc sed id semper risus. Sem et tortor consequat id. Morbi enim nunc faucibus a. At imperdiet dui accumsan sit amet nulla facilisi.
      
      Porttitor rhoncus dolor purus non. Dolor sit amet consectetur adipiscing elit. Sed viverra tellus in hac habitasse platea. Adipiscing elit ut aliquam purus. Nec dui nunc mattis enim ut tellus. Non consectetur a erat nam at lectus urna duis. Est placerat in egestas erat. At urna condimentum mattis pellentesque id. Nibh tellus molestie nunc non blandit massa. Vitae suscipit tellus mauris a diam maecenas sed. Duis at consectetur lorem donec massa sapien. Erat imperdiet sed euismod nisi.
      
      Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Cum sociis natoque penatibus et magnis. Consectetur purus ut faucibus pulvinar. Tellus orci ac auctor augue mauris augue neque gravida. Ac auctor augue mauris augue neque gravida in fermentum. Sed arcu non odio euismod lacinia. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Pharetra sit amet aliquam id diam. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Ornare arcu dui vivamus arcu felis. Dolor magna eget est lorem ipsum dolor sit amet. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Blandit massa enim nec dui nunc. Etiam tempor orci eu lobortis elementum.
      
      Libero volutpat sed cras ornare arcu. Urna cursus eget nunc scelerisque viverra. Eu sem integer vitae justo eget magna fermentum iaculis. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Congue eu consequat ac felis donec. Massa sapien faucibus et molestie. Facilisi morbi tempus iaculis urna id. Elit ullamcorper dignissim cras tincidunt. Et ligula ullamcorper malesuada proin libero nunc. Pellentesque habitant morbi tristique senectus et netus."
   end

end
